[package]
name = "rust-edit"
version = "0.1.0"
edition = "2024"
authors = ["ReeZey", "VilleOlof"]

[dependencies]
simdnbt = "0.7.1"
mca = "1.1.0"
thiserror = "2"
flate2 = "1.1.2"
rayon = "1.10"

[features]
spigot = []

[profile.speed]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
