[package]
name = "nbtedit"
version = "0.1.0"
edition = "2024"
authors = ["ReeZey", "VilleOlof"]

[dependencies]
fastnbt = "2.5.0"
flate2 = "1.1.2"
mca = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
