[package]
name = "rust-edit"
version = "0.1.0"
edition = "2024"
authors = ["ReeZey", "VilleOlof"]

[dependencies]
fastnbt = "2.5.0"
flate2 = "1.1.2"
mca = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
rayon = "1.10"

[features]
spigot = []
